def buscar_motivo(s, t):
    posiciones = []  # Lista para almacenar las posiciones donde aparece t en s
    
    for i in range(len(s) - len(t) + 1):  # Recorrer s hasta donde t pueda encajar
        if s[i:i+len(t)] == t:  # Verificar si la subcadena coincide con t
            posiciones.append(i + 1)  # Se usa i + 1 porque el índice en el problema empieza en 1
    
    print(" ".join(map(str, posiciones)))  # Imprimir las posiciones separadas por espacio

# Entradas para resolver el caso
s = "AGGCAGTAATGCAGTAAGCAGTAAGAGCAGTAAGTGCAGTAATTCATATCCCTGCAGTAAGTGCAGTAAAAGCCGTCCCGCAGTAACGCCGTGCAGTAAAGCAGTAAGCAGTAATTCTCTACATGGCAGTAAAGCAGTAAATGCAGTAACTGGATAAAGCAGTAAGCAGTAATGCAGTAACGGCAGTAAGCAGCAGTAAAAGCAGTAAGCAGTAAGGCAGTAATGCTTCAGCAGTAAGCAGTAATAGTGACGCAGTAATAGGAGCAGTAAGCAGTAATTGCAGTAAGGTAGCAGTAAGCAGTAAGCTTTGCAGTAAAGCAGTAAGCAGTAAAGCAGTAACGCAGCAGTAACCTAGCAGTAAGTTGCAGTAAGACCGAAGTTGATACAAAGCAGTAAAATTTGATGCAGTAAAGAGATTCCCCGCAGTAACTGGTGCAGTAATGCAGTAACCGGCAGTAAAAGCATGAGGGCAGTAAGCAGTAAAAGCAGTAAAACGCAGTAAGCAGTAAGCAGTAAGCAGTAAGCAGTAAAGCGCAGTAAGGCAGTAAACGACACGTAGTGTTGCAGTAAGCAGTAATAGGCAGTAAATGGCAGTAACCTTCTAAACCTGCAGTAACGTGGCAGTAAGCGGCAGTAAAAGCAGTAACAAGCAGTAAACCACTGCAGTAAGCAGTAAGCAGTAAAGTTGCGGCGCAGTAAGGCAGTAAGCAGTAACGCGCAGTAACCGCAGTAAACGTAGCAGTAAATCACCGCAGTAAGCAGTAATTGAGTATGCAGTAAGCAGTAAGTATAGTAGGCAGTAAGGCAGTAATGCAGTAATACCGCAGTAAGTCCGCAGTAAATTGCAGTAAGCAGTAAGCAGTAATTGCAGTAACGCAGTAAGGGCAGTAAATTTAAGCGCAGTAAGCAGTAACTACGGCAGTAAGCAGTAACACCGCAGTAAAGAGCAGTAAGCAGTAAGCAGTAAGGCAGTAAGGCAGTAAAGCAGTAA"
t = "GCAGTAAGC"
#Imprimir resultado del code
buscar_motivo(s, t)
